spring.application.name=springboot-mybatis-practice
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/mikasa
spring.datasource.username=root
spring.datasource.password=888888